import { useEffect, useState } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'

const links = [{ to: '/dashboard', label: 'Dashboard', icon: '◫' }, { to: '/vehicles', label: 'Vehículos', icon: '▣' }, { to: '/salidas', label: 'Registro de Salidas', icon: '↗' }]

export function AppLayout() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [open, setOpen] = useState(false)
  const leave = () => { logout(); navigate('/login') }
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [])
  const menu = <><div className="mb-8 flex items-center gap-3 px-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 font-bold text-slate-950">S</span><div><p className="font-bold tracking-wide">SIGEFLOT WEB</p><p className="text-xs text-slate-400">Gestión de flota</p></div></div><nav className="flex flex-col gap-2">{links.filter(link => link.to !== '/salidas' || user?.rol !== 'CONSULTA').map(link => <NavLink onClick={() => setOpen(false)} key={link.to} to={link.to} className={({ isActive }) => `flex min-h-11 items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${isActive ? 'bg-cyan-400 text-slate-950' : 'text-slate-300 hover:bg-slate-800 hover:text-white'}`}><span>{link.icon}</span>{link.label}</NavLink>)}</nav><button onClick={leave} className="mt-8 flex min-h-11 w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm text-slate-300 hover:bg-slate-800 hover:text-white">↪ Cerrar sesión</button></>
  return <div className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-800 md:flex"><aside className="hidden bg-slate-950 px-4 py-5 text-slate-100 md:block md:w-64 md:shrink-0">{menu}</aside>{open && <div className="fixed inset-0 z-30 overflow-hidden md:hidden"><button aria-label="Cerrar menú" onClick={() => setOpen(false)} className="absolute inset-0 bg-slate-950/50" /><aside aria-label="Menú de navegación" className="relative h-full w-72 max-w-[calc(100vw-2rem)] overflow-y-auto bg-slate-950 px-4 py-5 text-slate-100 shadow-2xl"><button aria-label="Cerrar menú" onClick={() => setOpen(false)} className="mb-4 grid min-h-11 min-w-11 place-items-center rounded-lg text-xl hover:bg-slate-800">×</button>{menu}</aside></div>}<div className="min-w-0 flex-1"><header className="flex min-h-16 items-center justify-between border-b border-slate-200 bg-white px-4 py-3 sm:px-8"><div className="flex items-center gap-3"><button aria-label="Abrir menú" onClick={() => setOpen(true)} className="grid min-h-11 min-w-11 place-items-center rounded-lg text-xl hover:bg-slate-100 md:hidden">☰</button><div><h1 className="font-bold text-slate-900">SIGEFLOT WEB</h1><p className="hidden text-xs text-slate-500 sm:block">Sistema Integral de Gestión de Flota y Mantenimiento Vehicular</p></div></div><div className="max-w-35 text-right"><p className="truncate text-sm font-semibold">{user?.nombres} {user?.apellidos}</p><p className="text-xs font-medium tracking-wide text-cyan-700">{user?.rol}</p></div></header><main className="mx-auto max-w-7xl p-4 sm:p-8"><Outlet /></main></div></div>
}
