import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ApiError, api } from '../services/api'
import type { MaintenanceCatalogItem, OrderDetail, OrderProvider } from '../types/api'

export function EditOrderPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [order,setOrder]=useState<OrderDetail|null>(null); const [providers,setProviders]=useState<OrderProvider[]>([]); const [catalog,setCatalog]=useState<MaintenanceCatalogItem[]>([]); const [selected,setSelected]=useState<number[]>([]); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  useEffect(()=>{ if(!id)return; Promise.all([api.getOrder(+id),api.orderProviders(),api.maintenanceCatalog()]).then(([o,p,c])=>{setOrder(o);setProviders(p);setCatalog(c);setSelected(o.preventivos.map(x=>x.id))}).catch(()=>setError('No se pudo cargar la orden.')) },[id])
  if(!order)return <p className="p-6">Cargando orden…</p>
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const mileage=String(f.get('km')??'');try{await api.updateOrder(order.id,{kilometraje_orden:mileage===''?null:Number(mileage),proveedor_id:f.get('provider')?Number(f.get('provider')):null,preventivo_ids:selected,descripcion_correctivo:String(f.get('correctivo')||'')||null,monto:f.get('monto')===''?null:Number(f.get('monto')),dias_parada:f.get('dias')===''?null:Number(f.get('dias'))});navigate(`/ordenes/${order.id}`)}catch(e){setError(e instanceof ApiError?e.message:'No se pudo guardar.')}finally{setSaving(false)}}
  return <form onSubmit={submit} className="mx-auto grid max-w-4xl gap-4"><Link to={`/ordenes/${order.id}`} className="min-h-11 text-cyan-700">← Volver</Link><h2 className="text-2xl font-bold">Editar orden {order.numero_orden}</h2><p>Fecha: {order.fecha || '—'} · Vehículo: {order.placa || '—'}</p><div className="grid gap-3 rounded-xl bg-white p-5 sm:grid-cols-2"><label>Kilometraje<input name="km" type="number" min="0" defaultValue={order.kilometraje_orden ?? ''} className="mt-1 min-h-11 w-full border p-2"/></label><label>Proveedor<select name="provider" defaultValue={order.proveedor_id ?? ''} className="mt-1 min-h-11 w-full border p-2"><option value="">Sin proveedor</option>{providers.map(p=><option key={p.id} value={p.id}>{p.razon_social}</option>)}</select></label><label>Monto<input name="monto" type="number" min="0" step="0.01" defaultValue={order.monto ?? ''} className="mt-1 min-h-11 w-full border p-2"/></label><label>Días de parada<input name="dias" type="number" min="0" defaultValue={order.dias_parada ?? ''} className="mt-1 min-h-11 w-full border p-2"/></label></div><section className="rounded-xl bg-white p-5"><h3 className="font-bold">Preventivos</h3>{catalog.map(c=><label key={c.id} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(x=>x.includes(c.id)?x.filter(i=>i!==c.id):[...x,c.id])}/>{c.tarea}</label>)}</section><label>Correctivo<textarea name="correctivo" defaultValue={order.descripcion_correctivo ?? ''} className="min-h-28 w-full border p-2"/></label>{error&&<p role="alert">{error}</p>}<button disabled={saving} className="min-h-11 rounded bg-cyan-700 text-white">{saving?'Guardando…':'Guardar cambios'}</button></form>
}
