import { useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiError } from '../services/api'
import { useAuth } from '../contexts/AuthContext'

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSending(true); try { await login(email, password); navigate('/dashboard') } catch (err) { setError(err instanceof ApiError && err.status === 401 ? 'Correo o contraseña inválidos.' : 'No se pudo iniciar sesión. Verifique la conexión.') } finally { setSending(false) } }
  return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top_right,_#155e75,_transparent_45%),linear-gradient(135deg,_#071522,_#102b45)] p-5"><section className="w-full max-w-md rounded-2xl bg-white p-7 shadow-2xl sm:p-9"><div className="mb-8"><span className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-400 text-xl font-bold text-slate-950">S</span><h1 className="mt-5 text-2xl font-bold text-slate-950">SIGEFLOT WEB</h1><p className="mt-1 text-sm leading-5 text-slate-500">Sistema Integral de Gestión de Flota y Mantenimiento Vehicular</p></div><form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium">Correo electrónico<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100" /></label><label className="block text-sm font-medium">Contraseña<input required type="password" minLength={12} value={password} onChange={e => setPassword(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100" /></label>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={sending} className="w-full rounded-lg bg-cyan-700 px-4 py-2.5 font-semibold text-white hover:bg-cyan-800 disabled:opacity-60">{sending ? 'Ingresando…' : 'Iniciar sesión'}</button></form></section></main>
}
