import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { ApiError, api } from '../services/api'
import type { OrderAuditResponse, OrderDetail } from '../types/api'
const show = (v: unknown) => v === null || v === undefined || v === '' ? '—' : String(v)
export function OrderDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const [order,setOrder]=useState<OrderDetail|null>(null); const [audit,setAudit]=useState<OrderAuditResponse>([]); const [error,setError]=useState(''); const [confirm,setConfirm]=useState(false); const [closing,setClosing]=useState(false)
  const load=()=>{if(!id)return;api.getOrder(+id).then(setOrder).catch(e=>setError(e instanceof ApiError?e.message:'No se pudo cargar.'));api.getOrderAudit(+id).then(setAudit).catch(()=>{})}; useEffect(load,[id])
  if(error)return <p role="alert">{error}</p>; if(!order)return <p>Cargando orden…</p>
  const canMutate=!order.es_historico&&['ADMINISTRADOR','MECANICO'].includes(user?.rol||''); const editable=canMutate&&order.estado==='ABIERTA'
  const close=async()=>{setClosing(true);try{await api.closeOrder(order.id);setConfirm(false);load()}catch(e){setError(e instanceof ApiError?e.message:'No se pudo cerrar.')}finally{setClosing(false)}}
  return <div className="mx-auto max-w-4xl"><Link to="/ordenes" className="min-h-11 text-cyan-700">← Volver a Órdenes</Link><h2 className="mt-3 text-2xl font-bold">Orden {order.numero_orden}</h2>{order.es_historico&&<p className="mt-2 rounded bg-slate-100 p-3">Histórica - solo lectura</p>}<p className="mt-2">Estado: <b>{order.estado}</b></p>{editable&&<div className="mt-3 flex gap-2"><Link to={`/ordenes/${order.id}/editar`} className="min-h-11 bg-cyan-700 px-4 py-3 text-white">Editar Orden</Link><button onClick={()=>setConfirm(true)} className="min-h-11 border px-4">Cerrar Orden</button></div>}<section className="mt-5 rounded-xl bg-white p-5"><h3 className="font-bold">Estado de archivo</h3>{canMutate?<select value={order.estado_archivo||'PENDIENTE'} onChange={async e=>{await api.updateOrderArchive(order.id,{estado_archivo:e.target.value as 'PENDIENTE'|'ARCHIVADO'});load()}} className="mt-2 min-h-11 border p-2"><option>PENDIENTE</option><option>ARCHIVADO</option></select>:<p>{show(order.estado_archivo)}</p>}</section><section className="mt-5 rounded-xl bg-white p-5"><p>Fecha: {show(order.fecha)} · Placa: {show(order.placa)} · Kilometraje: {show(order.kilometraje_orden)}</p><p>Proveedor: {show(order.proveedor)}</p><p>Correctivo: {show(order.descripcion_correctivo)}</p></section><section className="mt-5 rounded-xl bg-white p-5"><h3 className="font-bold">Historial de cambios</h3>{audit.length?audit.map(a=><article key={`${a.accion}-${a.fecha_hora}`} className="border-b py-3"><b>{a.accion}</b><p>{new Date(a.fecha_hora).toLocaleString('es-PE')} · {a.usuario}</p>{Object.entries(a.cambios).map(([key,change])=><p key={key}>{key}: {show(change.antes)} → {show(change.despues)}</p>)}</article>):<p>No existen cambios operativos registrados.</p>}</section>{confirm&&<div className="fixed inset-0 grid place-items-center bg-slate-950/50 p-4"><div className="rounded-xl bg-white p-6"><h3>¿Confirmar cierre de la orden?</h3><p>Una orden cerrada no podrá editarse en esta fase.</p><button onClick={()=>setConfirm(false)} className="min-h-11 px-4">Cancelar</button><button disabled={closing} onClick={close} className="min-h-11 bg-cyan-700 px-4 text-white">Confirmar cierre</button></div></div>}</div>
}
