import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ApiError, api } from '../services/api'
import type { OrderFilters, OrderListResponse } from '../types/api'

const date = (value: string | null) => value ? new Intl.DateTimeFormat('es-PE').format(new Date(`${value}T00:00:00`)) : '—'
const km = (value: number | null) => value === null ? '—' : `${value.toLocaleString('es-PE')} km`
const badge = (value: string | null) => <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{value || '—'}</span>

export function OrdersPage() {
  const [filters, setFilters] = useState<OrderFilters>({ page: 1, page_size: 20 })
  const [data, setData] = useState<OrderListResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); api.orders(filters).then(setData).catch(err => setError(err instanceof ApiError ? err.message : 'No se pudieron cargar las órdenes.')).finally(() => setLoading(false)) }, 350); return () => clearTimeout(timer) }, [filters])
  const update = (key: keyof OrderFilters, value: string | boolean | undefined) => setFilters(current => ({ ...current, [key]: value, page: 1 }))
  const clear = () => setFilters({ page: 1, page_size: 20 })
  return <div><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-wider text-cyan-700">Mantenimiento</p><h2 className="mt-1 text-2xl font-bold text-slate-950">Órdenes de Servicio</h2><p className="mt-2 text-slate-600">Consulta y seguimiento de órdenes registradas.</p></div>
    <section className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Buscar por número de orden" value={filters.search || ''} onChange={e => update('search', e.target.value)} placeholder="Buscar por número" className="min-h-11 rounded-lg border border-slate-300 px-3" /><input aria-label="Filtrar por placa" value={filters.placa || ''} onChange={e => update('placa', e.target.value)} placeholder="Placa" className="min-h-11 rounded-lg border border-slate-300 px-3" /><input aria-label="Filtrar por estado" value={filters.estado || ''} onChange={e => update('estado', e.target.value)} placeholder="Estado" className="min-h-11 rounded-lg border border-slate-300 px-3" /><select aria-label="Estado archivo" value={filters.estado_archivo || ''} onChange={e => update('estado_archivo', e.target.value)} className="min-h-11 rounded-lg border border-slate-300 bg-white px-3"><option value="">Archivo: todos</option><option>PENDIENTE</option><option>ARCHIVADO</option></select><select aria-label="Tipo de orden" value={filters.es_historico === undefined ? '' : String(filters.es_historico)} onChange={e => update('es_historico', e.target.value === '' ? undefined : e.target.value === 'true')} className="min-h-11 rounded-lg border border-slate-300 bg-white px-3"><option value="">Todas</option><option value="false">Operativas</option><option value="true">Históricas</option></select><label className="text-sm">Desde<input aria-label="Fecha desde" type="date" value={filters.fecha_desde || ''} onChange={e => update('fecha_desde', e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3" /></label><label className="text-sm">Hasta<input aria-label="Fecha hasta" type="date" value={filters.fecha_hasta || ''} onChange={e => update('fecha_hasta', e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3" /></label><button onClick={clear} className="min-h-11 self-end rounded-lg border border-slate-300 px-4 font-semibold">Limpiar filtros</button></section>
    {error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}{loading ? <p className="p-8 text-slate-500">Cargando órdenes…</p> : data?.items.length === 0 ? <p className="mt-4 rounded-lg bg-white p-6 text-slate-600">No se encontraron órdenes con estos filtros.</p> : <><div className="mt-5 hidden overflow-x-auto rounded-xl border border-slate-200 bg-white md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['Orden','Fecha','Placa','Kilometraje','Proveedor','Estado','Archivo','Origen','Acción'].map(h => <th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{data?.items.map(item => <tr key={item.id} className="border-t"><td className="px-3 py-3 font-semibold">{item.numero_orden}</td><td className="px-3 py-3">{date(item.fecha)}</td><td className="px-3 py-3">{item.placa || '—'}</td><td className="px-3 py-3">{km(item.kilometraje_orden)}</td><td className="px-3 py-3">{item.proveedor || '—'}</td><td className="px-3 py-3">{badge(item.estado)}</td><td className="px-3 py-3">{badge(item.estado_archivo)}</td><td className="px-3 py-3">{item.es_historico ? 'Histórica' : 'Operativa'}</td><td className="px-3 py-3"><Link className="font-semibold text-cyan-700" to={`/ordenes/${item.id}`}>Ver detalle</Link></td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 md:hidden">{data?.items.map(item => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold">{item.numero_orden}</h3><p className="mt-1 text-sm text-slate-600">{date(item.fecha)}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><dt>Placa</dt><dd>{item.placa || '—'}</dd><dt>Kilometraje</dt><dd>{km(item.kilometraje_orden)}</dd><dt>Proveedor</dt><dd>{item.proveedor || '—'}</dd><dt>Origen</dt><dd>{item.es_historico ? 'Histórica' : 'Operativa'}</dd></dl><Link className="mt-4 flex min-h-11 items-center justify-center rounded-lg border border-cyan-700 font-semibold text-cyan-800" to={`/ordenes/${item.id}`}>Ver detalle</Link></article>)}</div></>}
    {data && <div className="mt-5 flex items-center justify-between"><p className="text-sm text-slate-600">{data.total} órdenes</p><div className="flex gap-2"><button disabled={data.page <= 1} onClick={() => update('page', String(data.page - 1))} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">Anterior</button><span className="grid min-h-11 place-items-center px-2 text-sm">{data.page} / {data.pages || 1}</span><button disabled={data.page >= data.pages} onClick={() => update('page', String(data.page + 1))} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">Siguiente</button></div></div>}</div>
}
